{{- if .Values.nfsServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-server
spec:
  ports:
    - name: nfs
      port: {{ .Values.nfsServer.servicePort }}
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP
  selector:
    role: {{ include "peaka.fullname" . }}-nfs-server
{{- end -}}
