{{- if .Values.nfsServer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: {{ include "peaka.fullname" . }}-nfs-server
  template:
    metadata:
      labels:
        role: {{ include "peaka.fullname" . }}-nfs-server
    spec:
      restartPolicy: Always
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine
          env:
            - name: SHARED_DIRECTORY
              value: {{ .Values.nfsServer.persistentVolume.mountPath }}
          ports:
            - name: nfs
              containerPort: {{ .Values.nfsServer.deployment.containerPort }}
          {{- with .Values.nfsServer.deployment.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.nfsServer.persistentVolume.mountPath }}
              name: nfs-volume
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: {{ include "peaka.fullname" . }}-nfs-server
{{- end -}}