{{- if .Values.nfsServer.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfsServer.persistence.size }}
  {{- include "peaka.common.storage.class" (dict "persistence" .Values.nfsServer.persistence "global" .Values.global) | nindent 2 }}
{{- end }}
