{{- if .Values.nfsServer.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfsServer.persistentVolume.size | quote }}
{{- end }}
