{{- if .Values.peakaContainerRegistryAccessSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.peakaContainerRegistryAccessSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "peaka.imageRegistry.secret" . }}
{{- end }}
