apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peaka.fullname" . }}-jwt-rsa-secret
type: Opaque
data:
  publickey.pem: |
    {{ include "peaka.jwt.publicKey" . }}
  privatekey.pem: |
    {{ include "peaka.jwt.privateKey" . }}
