{{- if and .Values.externalObjectStore.tls.enabled .Values.externalObjectStore.tls.cert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peaka.fullname" . }}-objectstore-ca
  labels:
    {{- include "peaka.labels" . | nindent 4 }}
data:
  minio.crt: |
    {{- .Values.externalObjectStore.tls.cert | nindent 4 }}
{{- end }}
