{{- if .Values.redhatRegistryAccessSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redhatRegistryAccessSecret.name | default "redhat-registry" }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "peaka.redhatRegistry.secret" . }}
{{- end }}
