{{- if and .Values.tls.enabled (not .Values.tls.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peaka.fullname" . }}-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: {{ required "tls.cert is required when not using an existing secret" .Values.tls.cert | b64enc }}
  tls.key: {{ required "tls.key is required when not using an existing secret" .Values.tls.key | b64enc }}
{{- end }}
