apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "peaka.trino.coordinator" . }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.trino.coordinator.persistence.size }}
  {{- if ( include "peaka.trino.coordinator.storageClass" . ) }}
  storageClassName: {{ include "peaka.trino.coordinator.storageClass" . }}
  {{- end }}