apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "peaka.trino.coordinator" . }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.trino.coordinator.persistence.size }}
  {{- include "peaka.common.storage.class" (dict "persistence" .Values.trino.coordinator.persistence "global" .Values.global) | nindent 2 }}
