apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "peaka.trino.coordinator" . }}
  {{- if .Values.trino.coordinator.persistence.annotations }}
  annotations:
    {{- toYaml .Values.trino.coordinator.persistence.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.trino.coordinator.persistence.labels }}
  labels:
    {{- toYaml .Values.trino.coordinator.persistence.labels | nindent 4}}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.trino.coordinator.persistence.size }}
  {{- include "peaka.common.storage.class" (dict "persistence" .Values.trino.coordinator.persistence "global" .Values.global) | nindent 2 }}
