apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peaka.fullname" . }}-studio-predefined-users-secret
type: Opaque
stringData:
  predefined-users.json: {{ toJson (default (list) .Values.predefinedUsers) | quote }}
