apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peaka.fullname" . }}-be-studio-api
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-studio-api
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.studioApi.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-studio-api
      {{- include "peaka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-studio-api
        {{- include "peaka.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
        {{- range $_, $secret := .Values.additionalImagePullSecrets }}
        - name: {{ $secret }}
        {{- end }}
      initContainers:
        - name: data-migrator
          image: {{ default (include "peaka.image.registry" .) .Values.dataMigrator.image.registry }}/{{ .Values.dataMigrator.image.name }}:{{ .Values.dataMigrator.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.dataMigrator.image.imagePullPolicy }}
          env:
            - name: SERVICE_NAME
              value: be-studio-api
          envFrom:
            - configMapRef:
                name: {{ include "peaka.fullname" . }}-env-config
      containers:
        - name: studio-api
          image: {{ default (include "peaka.image.registry" .) .Values.studioApi.image.registry }}/{{ .Values.studioApi.image.name }}:{{ .Values.studioApi.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.studioApi.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ROOT_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "peaka.fullname" . }}-studio-root-user-secret
                  key: username
            - name: ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "peaka.fullname" . }}-studio-root-user-secret
                  key: password
          envFrom:
            - configMapRef:
                name: {{ include "peaka.fullname" . }}-env-config
          volumeMounts:
            - mountPath: /secrets/jwt/rsa
              name: jwt-rsa-secret
              readOnly: true
          {{- with .Values.studioApi.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.studioApi.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.studioApi.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: jwt-rsa-secret
          secret:
            secretName: {{ include "peaka.fullname" . }}-jwt-rsa-secret
      {{- if .Values.studioApi.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.studioApi.terminationGracePeriodSeconds }}
      {{- end }}
      {{- include "peaka.common.nodeSelector" ( dict "nodeSelector" .Values.studioApi.nodeSelector "global" $.Values.global) | nindent 6 }}
      {{- with .Values.studioApi.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "peaka.common.tolerations" ( dict "tolerations" .Values.studioApi.tolerations "global" $.Values.global) }}
