apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peaka.fullname" . }}-be-token-service
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-token-service
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tokenService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-token-service
      {{- include "peaka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-token-service
        {{- include "peaka.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
        {{- range $_, $secret := .Values.additionalImagePullSecrets }}
        - name: {{ $secret }}
        {{- end }}
      containers:
        - name: token-service
          image: {{ printf "%s/%s:%s" (include "peaka.image.registry" . ) .Values.tokenService.image.name .Values.tokenService.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.tokenService.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "peaka.fullname" . }}-env-config
          {{- with .Values.tokenService.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tokenService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tokenService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.tokenService.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.tokenService.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.tokenService.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tokenService.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
