{{- if $.Values.temporal.enabled }}
{{- if $.Values.temporal.admintools.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "peaka.temporal.componentname" (list . "admintools") }}
  labels:
    app.kubernetes.io/name: {{ include "peaka.temporal.name" . }}
    helm.sh/chart: {{ include "peaka.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: admintools
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  type: ClusterIP 
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh

  selector:
    app.kubernetes.io/name: {{ include "peaka.temporal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admintools
{{- end }}
{{- end }}
