{{- if $.Values.temporal.server.enabled }}
{{- range $service := (list "frontend" "history" "matching" "worker") }}
{{- $serviceValues := index $.Values.temporal.server $service -}}
{{- if and (gt ($serviceValues.replicaCount | int) 1) ($serviceValues.podDisruptionBudget) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "peaka.temporal.componentname" (list $ $service) }}-pdb
  labels:
    app.kubernetes.io/name: {{ include "peaka.temporal.name" $ }}
    helm.sh/chart: {{ include "peaka.chart" $ }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: {{ $service }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  {{ toYaml $serviceValues.podDisruptionBudget }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "peaka.temporal.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $service }}
{{- end }}
---
{{- end }}
{{- end }}
